"""partner skill per-star buff tiers

Revision ID: 603f3ceb3ff0
Revises: e53167a65ce5
Create Date: 2026-07-23 22:16:15.211577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '603f3ceb3ff0'
down_revision: Union[str, Sequence[str], None] = 'e53167a65ce5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partner_skill_buff_tier',
    sa.Column('partner_skill_id', sa.Integer(), nullable=False),
    sa.Column('star_level', sa.Integer(), nullable=False),
    sa.Column('buff_value', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['partner_skill_id'], ['partner_skill.id'], name=op.f('fk_partner_skill_buff_tier_partner_skill_id_partner_skill'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('partner_skill_id', 'star_level', name=op.f('pk_partner_skill_buff_tier'))
    )
    with op.batch_alter_table('partner_skill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('buff_mechanic', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('buff_max_stacks', sa.Integer(), nullable=True))
        batch_op.drop_column('buff_value')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partner_skill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('buff_value', sa.NUMERIC(precision=5, scale=4), nullable=True))
        batch_op.drop_column('buff_max_stacks')
        batch_op.drop_column('buff_mechanic')

    op.drop_table('partner_skill_buff_tier')
    # ### end Alembic commands ###
