"""partner skill weakness boost

Revision ID: 63199a6937a5
Revises: dd0ae5cd5949
Create Date: 2026-08-16 22:09:09.799490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63199a6937a5'
down_revision: Union[str, Sequence[str], None] = 'dd0ae5cd5949'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partner_skill_weakness_tier',
    sa.Column('partner_skill_id', sa.Integer(), nullable=False),
    sa.Column('star_level', sa.Integer(), nullable=False),
    sa.Column('buff_value', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['partner_skill_id'], ['partner_skill.id'], name=op.f('fk_partner_skill_weakness_tier_partner_skill_id_partner_skill'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('partner_skill_id', 'star_level', name=op.f('pk_partner_skill_weakness_tier'))
    )
    with op.batch_alter_table('partner_skill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weakness_element_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_partner_skill_weakness_element_id_element_type'), 'element_type', ['weakness_element_id'], ['id'], ondelete='RESTRICT')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partner_skill', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_partner_skill_weakness_element_id_element_type'), type_='foreignkey')
        batch_op.drop_column('weakness_element_id')

    op.drop_table('partner_skill_weakness_tier')
    # ### end Alembic commands ###
