"""initial schema: all tables per data-model.md

Revision ID: d5791f5828a2
Revises: 
Create Date: 2026-07-16 21:59:13.644123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5791f5828a2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boss',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_zh', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('defense_stat', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_boss'))
    )
    op.create_table('element_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_zh', sa.String(length=10), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_element_type')),
    sa.UniqueConstraint('code', name=op.f('uq_element_type_code')),
    sa.UniqueConstraint('name_zh', name=op.f('uq_element_type_name_zh'))
    )
    op.create_table('import_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=False),
    sa.Column('game_version', sa.String(length=20), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_log'))
    )
    op.create_table('pal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dev_name', sa.String(length=50), nullable=False),
    sa.Column('name_zh', sa.String(length=50), nullable=False),
    sa.Column('shot_attack_stat', sa.Integer(), nullable=False),
    sa.Column('melee_attack_stat', sa.Integer(), nullable=False),
    sa.Column('defense_stat', sa.Integer(), nullable=False),
    sa.Column('hp_stat', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pal')),
    sa.UniqueConstraint('dev_name', name=op.f('uq_pal_dev_name'))
    )
    with op.batch_alter_table('pal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pal_name_zh'), ['name_zh'], unique=False)

    op.create_table('work_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_zh', sa.String(length=20), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_type')),
    sa.UniqueConstraint('code', name=op.f('uq_work_type_code')),
    sa.UniqueConstraint('name_zh', name=op.f('uq_work_type_name_zh'))
    )
    op.create_table('active_skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_zh', sa.String(length=50), nullable=False),
    sa.Column('name_en', sa.String(length=50), nullable=False),
    sa.Column('element_id', sa.Integer(), nullable=False),
    sa.Column('power', sa.Integer(), nullable=False),
    sa.Column('cooldown_seconds', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['element_id'], ['element_type.id'], name=op.f('fk_active_skill_element_id_element_type'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_active_skill')),
    sa.UniqueConstraint('name_en', name=op.f('uq_active_skill_name_en'))
    )
    op.create_table('boss_element',
    sa.Column('boss_id', sa.Integer(), nullable=False),
    sa.Column('element_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['boss_id'], ['boss.id'], name=op.f('fk_boss_element_boss_id_boss'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['element_id'], ['element_type.id'], name=op.f('fk_boss_element_element_id_element_type'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('boss_id', 'element_id', name=op.f('pk_boss_element'))
    )
    op.create_table('pal_element',
    sa.Column('pal_id', sa.Integer(), nullable=False),
    sa.Column('element_id', sa.Integer(), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['element_id'], ['element_type.id'], name=op.f('fk_pal_element_element_id_element_type'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pal_id'], ['pal.id'], name=op.f('fk_pal_element_pal_id_pal'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pal_id', 'element_id', name=op.f('pk_pal_element'))
    )
    with op.batch_alter_table('pal_element', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pal_element_element_id'), ['element_id'], unique=False)

    op.create_table('pal_work_suitability',
    sa.Column('pal_id', sa.Integer(), nullable=False),
    sa.Column('work_type_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pal_id'], ['pal.id'], name=op.f('fk_pal_work_suitability_pal_id_pal'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_type_id'], ['work_type.id'], name=op.f('fk_pal_work_suitability_work_type_id_work_type'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pal_id', 'work_type_id', name=op.f('pk_pal_work_suitability'))
    )
    op.create_table('partner_skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pal_id', sa.Integer(), nullable=False),
    sa.Column('name_zh', sa.String(length=50), nullable=False),
    sa.Column('effect_type', sa.String(length=20), nullable=False),
    sa.Column('buff_target', sa.String(length=30), nullable=True),
    sa.Column('buff_element_id', sa.Integer(), nullable=True),
    sa.Column('buff_value', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('effect_raw', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['buff_element_id'], ['element_type.id'], name=op.f('fk_partner_skill_buff_element_id_element_type'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pal_id'], ['pal.id'], name=op.f('fk_partner_skill_pal_id_pal'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_partner_skill')),
    sa.UniqueConstraint('pal_id', name=op.f('uq_partner_skill_pal_id'))
    )
    op.create_table('type_matchup',
    sa.Column('attacker_element_id', sa.Integer(), nullable=False),
    sa.Column('defender_element_id', sa.Integer(), nullable=False),
    sa.Column('multiplier', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['attacker_element_id'], ['element_type.id'], name=op.f('fk_type_matchup_attacker_element_id_element_type')),
    sa.ForeignKeyConstraint(['defender_element_id'], ['element_type.id'], name=op.f('fk_type_matchup_defender_element_id_element_type')),
    sa.PrimaryKeyConstraint('attacker_element_id', 'defender_element_id', name=op.f('pk_type_matchup'))
    )
    op.create_table('pal_active_skill',
    sa.Column('pal_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('learned_level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pal_id'], ['pal.id'], name=op.f('fk_pal_active_skill_pal_id_pal'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['active_skill.id'], name=op.f('fk_pal_active_skill_skill_id_active_skill'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pal_id', 'skill_id', name=op.f('pk_pal_active_skill'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pal_active_skill')
    op.drop_table('type_matchup')
    op.drop_table('partner_skill')
    op.drop_table('pal_work_suitability')
    with op.batch_alter_table('pal_element', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pal_element_element_id'))

    op.drop_table('pal_element')
    op.drop_table('boss_element')
    op.drop_table('active_skill')
    op.drop_table('work_type')
    with op.batch_alter_table('pal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pal_name_zh'))

    op.drop_table('pal')
    op.drop_table('import_log')
    op.drop_table('element_type')
    op.drop_table('boss')
    # ### end Alembic commands ###
