"""partner skill activity effects

Revision ID: dd0ae5cd5949
Revises: 603f3ceb3ff0
Create Date: 2026-07-24 23:19:35.902662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd0ae5cd5949'
down_revision: Union[str, Sequence[str], None] = '603f3ceb3ff0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partner_skill_activity_effect',
    sa.Column('partner_skill_id', sa.Integer(), nullable=False),
    sa.Column('effect_type', sa.String(length=50), nullable=False),
    sa.Column('star_level', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['partner_skill_id'], ['partner_skill.id'], name=op.f('fk_partner_skill_activity_effect_partner_skill_id_partner_skill'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('partner_skill_id', 'effect_type', 'star_level', name=op.f('pk_partner_skill_activity_effect'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('partner_skill_activity_effect')
    # ### end Alembic commands ###
