"""add category to active_skill

Revision ID: e53167a65ce5
Revises: d5791f5828a2
Create Date: 2026-07-16 22:09:35.174988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e53167a65ce5'
down_revision: Union[str, Sequence[str], None] = 'd5791f5828a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('active_skill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('active_skill', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
